name: lexicode_app
description: "LexiCode DualCore Assistant - AI Code Review & English Learning"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  fl_chart: ^1.2.0
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^2.0.1
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  email_validator: ^3.0.0
  http: ^1.2.2
  http_parser: ^4.1.0
  cloud_functions: ^6.1.0
  google_generative_ai: ^0.4.7
  flutter_tts: ^4.2.0
  speech_to_text: ^7.0.0
  record: ^6.2.0
  audioplayers: ^6.1.0
  uuid: ^4.5.1
  firebase_storage: ^13.2.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  crypto: ^3.0.5
  app_links: ^7.0.0
  google_sign_in: ^7.2.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
